### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b/lora/sft
trust_remote_code: true

### method
finetuning_type: lora

### dataset
# task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
# template: fewshot
# lang: en
# n_shot: 5
eval_dataset: judge_test
template: llama3
cutoff_len: 2048
# max_samples: 50
overwrite_cache: true
preprocessing_num_workers: 16

### output
save_dir: saves/llama3-8b/lora/eval

### eval
batch_size: 4
