### model
model_name_or_path: /mnt/afs/share/llama3.1-8b-base
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
# lora_rank: 16
# deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: judge
template: llama3
cutoff_len: 2048
generation_max_length: 3000
max_new_tokens: 3000
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/sft_0123_lorarank8_bs2_newmetric
logging_steps: 500
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: judge_test
predict_with_generate: true
# val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### SwanLab
use_swanlab: true
swanlab_run_name: sft_0123_lorarank8_bs2_newmetric # optionald